version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edition2ld
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: iworld023@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
      MAX_CONTENT_LENGTH: 104857600
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: